In [1]:
import duckdb
con = duckdb.connect("../data/capstone_data.duckdb")

### Sanity Check of data and columns

In [8]:
con.execute("DESCRIBE customers").df()

                   column_name column_type null   key default extra
0                   CustomerID     VARCHAR  YES  None    None  None
1                   Individual     VARCHAR  YES  None    None  None
2                          Age      DOUBLE  YES  None    None  None
3                       Gender     VARCHAR  YES  None    None  None
4                    NAICSCode      DOUBLE  YES  None    None  None
5         OriginalCustomerDate        DATE  YES  None    None  None
6            RelationshipYears      DOUBLE  YES  None    None  None
7           RelationshipMonths      DOUBLE  YES  None    None  None
8                 BangorWealth     BOOLEAN  YES  None    None  None
9                      Payroll     BOOLEAN  YES  None    None  None
10                    Merchant     BOOLEAN  YES  None    None  None
11                         TPS     BOOLEAN  YES  None    None  None
12               PlingCustomer     BOOLEAN  YES  None    None  None
13                ABLECustomer     BOOLEAN  YES  None    None  None
14          TimeDepositAccount     VARCHAR  YES  None    None  None
15              DepositAccount     VARCHAR  YES  None    None  None
16                 LoanAccount     VARCHAR  YES  None    None  None
17           CreditCardAccount     VARCHAR  YES  None    None  None
18               ActiveATMCard     VARCHAR  YES  None    None  None
19             ActiveDebitCard     VARCHAR  YES  None    None  None
20            NumberActiveDDAs      DOUBLE  YES  None    None  None
21    NumberActiveTimeDeposits      DOUBLE  YES  None    None  None
22           NumberActiveLoans      DOUBLE  YES  None    None  None
23       NumberCreditCardAccts      DOUBLE  YES  None    None  None
24  PrimaryBankingCustomerFlag     VARCHAR  YES  None    None  None

In [5]:
# Get column names dynamically
cols = con.execute("DESCRIBE customers").df()['column_name'].tolist()

# Querying missing values and looping through all columns
null_checks = ', '.join([f"COUNT(*) - COUNT({c}) AS {c}" for c in cols])
missing = con.execute(f"SELECT {null_checks} FROM customers").fetchone()

for col, nulls in zip(cols, missing):
    if nulls > 0:
        print(f"  {col}: {nulls:,} missing")

  NAICSCode: 234,887 missing
  OriginalCustomerDate: 24 missing
  RelationshipYears: 24 missing
  RelationshipMonths: 24 missing

### Customers Overview

In [6]:
query = con.execute("""
                    SELECT 
                    COUNT(*) AS total_customers,
                    COUNT(distinct CustomerID) AS unique_customers,
                    SUM(CASE WHEN Individual = 'Y' THEN 1 ELSE 0 END) AS individuals,
                    SUM(CASE WHEN Individual = 'N' THEN 1 ELSE 0 END) AS non_individuals
                    FROM customers
                    """).fetchone()

print(f"Total customer rows: {query[0]:,}")
print(f"Total unique customers: {query[1]:,}")
print(f"Total individual customers: {query[2]:,}")
print(f"Total non-individual customers: {query[3]:,}")

Total customer rows: 276,838
Total unique customers: 276,837
Total individual customers: 236,428
Total non-individual customers: 40,410

### Age Distribution

In [7]:
query = con.execute("""
    SELECT 
        COUNT(*) AS total,
        COUNT(Age) AS with_age,
        ROUND(MIN(Age), 1) AS min_age,
        ROUND(MAX(Age), 1) AS max_age,
        ROUND(AVG(Age), 1) AS avg_age,
        ROUND(MEDIAN(Age), 1) AS median_age
    FROM customers
""").fetchone()

print(f"Customers with age: {query[1]:,} / {query[0]:,}")
print(f"Min age:    {query[2]}")
print(f"Max age:    {query[3]}")
print(f"Mean age :   {query[4]}")
print(f"Median age: {query[5]}")

Customers with age: 276,838 / 276,838
Min age:    0.0
Max age:    126.0
Mean age :   41.9
Median age: 43.0

In [3]:
query = con.execute("""
    SELECT *
    FROM customers
    WHERE Age > 100
    ORDER BY Age DESC
""").df()

print(query.T)

                                            0                    1    \
CustomerID                            BSB505021            BSB104853
Individual                                    Y                    Y
Age                                       126.0                126.0
Gender
NAICSCode                                   NaN                  NaN
OriginalCustomerDate        1982-01-21 00:00:00  1970-06-29 00:00:00
RelationshipYears                          44.0                 56.0
RelationshipMonths                        528.0                667.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            N                    N
DepositAccount                                Y                    Y
LoanAccount                                   N                    N
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            1.0                  1.0
NumberActiveTimeDeposits                    0.0                  0.0
NumberActiveLoans                           0.0                  0.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    N                    N

                                            2                    3    \
CustomerID                            BSB152620            BSB197835
Individual                                    N                    N
Age                                       126.0                126.0
Gender                                        O                    M
NAICSCode                              531110.0             926150.0
OriginalCustomerDate        2010-05-12 00:00:00  2019-04-10 00:00:00
RelationshipYears                          16.0                  7.0
RelationshipMonths                        188.0                 81.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                        True                 True
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            N                    N
DepositAccount                                Y                    Y
LoanAccount                                   N                    N
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            2.0                  2.0
NumberActiveTimeDeposits                    0.0                  0.0
NumberActiveLoans                           0.0                  0.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    Y                    Y

                                            4                    5    \
CustomerID                            BSB179775            BSB036562
Individual                                    N                    N
Age                                       125.0                125.0
Gender
NAICSCode                              813930.0             813410.0
OriginalCustomerDate        2004-01-22 00:00:00  1998-12-01 00:00:00
RelationshipYears                          22.0                 28.0
RelationshipMonths                        264.0                325.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            N                    N
DepositAccount                                Y                    Y
LoanAccount                                   N                    Y
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    Y
NumberActiveDDAs                            2.0                 10.0
NumberActiveTimeDeposits                    0.0                  0.0
NumberActiveLoans                           0.0                  1.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    N                    Y

                                            6                    7    \
CustomerID                            BSB455643            BSB169978
Individual                                    Y                    Y
Age                                       120.0                118.0
Gender                                        F
NAICSCode                                   NaN                  NaN
OriginalCustomerDate        1992-08-21 00:00:00  1989-11-08 00:00:00
RelationshipYears                          34.0                 37.0
RelationshipMonths                        401.0                434.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            N                    N
DepositAccount                                Y                    Y
LoanAccount                                   N                    N
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            1.0                  1.0
NumberActiveTimeDeposits                    0.0                  0.0
NumberActiveLoans                           0.0                  0.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    Y                    N

                                            8                    9    ...  \
CustomerID                            BSB170153            BSB368581  ...
Individual                                    Y                    Y  ...
Age                                       118.0                115.0  ...
Gender                                        M                    M  ...
NAICSCode                                   NaN                  NaN  ...
OriginalCustomerDate        1996-10-03 00:00:00  1977-03-21 00:00:00  ...
RelationshipYears                          30.0                 49.0  ...
RelationshipMonths                        351.0                586.0  ...
BangorWealth                              False                False  ...
Payroll                                   False                False  ...
Merchant                                  False                False  ...
TPS                                       False                False  ...
PlingCustomer                             False                False  ...
ABLECustomer                              False                False  ...
TimeDepositAccount                            N                    N  ...
DepositAccount                                Y                    Y  ...
LoanAccount                                   N                    N  ...
CreditCardAccount                             N                    N  ...
ActiveATMCard                                 N                    N  ...
ActiveDebitCard                               N                    N  ...
NumberActiveDDAs                            1.0                  1.0  ...
NumberActiveTimeDeposits                    0.0                  0.0  ...
NumberActiveLoans                           0.0                  0.0  ...
NumberCreditCardAccts                       0.0                  0.0  ...
PrimaryBankingCustomerFlag                    Y                    N  ...

                                            129                  130  \
CustomerID                            BSB367098            BSB368063
Individual                                    Y                    Y
Age                                       101.0                101.0
Gender                                        F                    F
NAICSCode                                   NaN                  NaN
OriginalCustomerDate        2001-12-31 00:00:00  1987-10-29 00:00:00
RelationshipYears                          25.0                 39.0
RelationshipMonths                        289.0                459.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            Y                    N
DepositAccount                                N                    Y
LoanAccount                                   N                    N
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            0.0                  1.0
NumberActiveTimeDeposits                    1.0                  0.0
NumberActiveLoans                           0.0                  0.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    N                    N

                                            131                  132  \
CustomerID                            BSB299978            BSB275638
Individual                                    Y                    Y
Age                                       101.0                101.0
Gender                                        F                    F
NAICSCode                                   NaN                  NaN
OriginalCustomerDate        2020-08-05 00:00:00  1983-07-08 00:00:00
RelationshipYears                           6.0                 43.0
RelationshipMonths                         65.0                510.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            N                    Y
DepositAccount                                Y                    Y
LoanAccount                                   N                    Y
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            2.0                  2.0
NumberActiveTimeDeposits                    0.0                  2.0
NumberActiveLoans                           0.0                  1.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    Y                    Y

                                            133                  134  \
CustomerID                            BSB414250            BSB353308
Individual                                    Y                    Y
Age                                       101.0                101.0
Gender                                        M                    F
NAICSCode                                   NaN                  NaN
OriginalCustomerDate        1969-01-01 00:00:00  2022-10-29 00:00:00
RelationshipYears                          57.0                  4.0
RelationshipMonths                        684.0                 39.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            Y                    N
DepositAccount                                Y                    Y
LoanAccount                                   N                    N
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            1.0                  1.0
NumberActiveTimeDeposits                    1.0                  0.0
NumberActiveLoans                           0.0                  0.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    Y                    Y

                                            135                  136  \
CustomerID                            BSB453110            BSB268948
Individual                                    Y                    Y
Age                                       101.0                101.0
Gender                                        M                    F
NAICSCode                                   NaN                  NaN
OriginalCustomerDate        1979-12-24 00:00:00  2013-10-29 00:00:00
RelationshipYears                          47.0                 13.0
RelationshipMonths                        553.0                147.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            N                    N
DepositAccount                                Y                    Y
LoanAccount                                   N                    N
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            1.0                  2.0
NumberActiveTimeDeposits                    0.0                  0.0
NumberActiveLoans                           0.0                  0.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    N                    Y

                                            137                  138
CustomerID                            BSB454011            BSB348781
Individual                                    Y                    Y
Age                                       101.0                101.0
Gender                                        M                    F
NAICSCode                                   NaN                  NaN
OriginalCustomerDate        1998-01-27 00:00:00  1991-09-06 00:00:00
RelationshipYears                          28.0                 35.0
RelationshipMonths                        336.0                412.0
BangorWealth                              False                False
Payroll                                   False                False
Merchant                                  False                False
TPS                                       False                False
PlingCustomer                             False                False
ABLECustomer                              False                False
TimeDepositAccount                            N                    N
DepositAccount                                Y                    Y
LoanAccount                                   N                    N
CreditCardAccount                             N                    N
ActiveATMCard                                 N                    N
ActiveDebitCard                               N                    N
NumberActiveDDAs                            1.0                  1.0
NumberActiveTimeDeposits                    0.0                  0.0
NumberActiveLoans                           0.0                  0.0
NumberCreditCardAccts                       0.0                  0.0
PrimaryBankingCustomerFlag                    Y                    N

[25 rows x 139 columns]

### Analyzing Relationships

In [8]:
query = con.execute("""
    SELECT 
        ROUND(MIN(RelationshipYears), 1) AS min_years,
        ROUND(MAX(RelationshipYears), 1) AS max_years,
        ROUND(AVG(RelationshipYears), 1) AS avg_years,
        ROUND(MEDIAN(RelationshipYears), 1) AS median_years
    FROM customers
""").fetchone()

print(f"Min rel age:    {query[0]} years")
print(f"Max rel age:    {query[1]} years")
print(f"Mean rel age:   {query[2]} years")
print(f"Median rel age: {query[3]} years")

Min rel age:    0.0 years
Max rel age:    85.0 years
Mean rel age:   13.3 years
Median rel age: 10.0 years

### Various products and holdings

In [9]:
query = con.execute("""
    SELECT 
        SUM(CASE WHEN ActiveDebitCard = 'Y' THEN 1 ELSE 0 END) AS active_debit,
        SUM(CASE WHEN ActiveATMCard = 'Y' THEN 1 ELSE 0 END) AS active_atm,
        SUM(CASE WHEN DepositAccount = 'Y' THEN 1 ELSE 0 END) AS deposit_acct,
        SUM(CASE WHEN LoanAccount = 'Y' THEN 1 ELSE 0 END) AS loan_acct,
        SUM(CASE WHEN CreditCardAccount = 'Y' THEN 1 ELSE 0 END) AS credit_card,
        SUM(CASE WHEN TimeDepositAccount = 'Y' THEN 1 ELSE 0 END) AS time_deposit,
        COUNT(*) AS total
    FROM customers
""").fetchone()

total = query[6]
print(f"Active Debit Card:    {query[0]:,} ({query[0]/total*100:.1f}%)")
print(f"Active ATM Card:      {query[1]:,} ({query[1]/total*100:.1f}%)")
print(f"Deposit Account:      {query[2]:,} ({query[2]/total*100:.1f}%)")
print(f"Loan Account:         {query[3]:,} ({query[3]/total*100:.1f}%)")
print(f"Credit Card Account:  {query[4]:,} ({query[4]/total*100:.1f}%)")
print(f"Time Deposit Account: {query[5]:,} ({query[5]/total*100:.1f}%)")

Active Debit Card:    180,912 (65.3%)
Active ATM Card:      8,230 (3.0%)
Deposit Account:      260,163 (94.0%)
Loan Account:         57,175 (20.7%)
Credit Card Account:  6,391 (2.3%)
Time Deposit Account: 14,336 (5.2%)

### Checking boolean value columns -

In [10]:
query = con.execute("""
    SELECT 
        SUM(CASE WHEN TPS = true THEN 1 ELSE 0 END) AS tps,
        SUM(CASE WHEN Payroll = true THEN 1 ELSE 0 END) AS payroll,
        SUM(CASE WHEN Merchant = true THEN 1 ELSE 0 END) AS merchant,
        SUM(CASE WHEN BangorWealth = true THEN 1 ELSE 0 END) AS bangor_wealth,
        SUM(CASE WHEN PlingCustomer = true THEN 1 ELSE 0 END) AS pling,
        SUM(CASE WHEN ABLECustomer = true THEN 1 ELSE 0 END) AS able,
        COUNT(*) AS total
    FROM customers
""").fetchone()

total = query[6]
print(f"TPS (Treasury and Payment Services): {query[0]:,} ({query[0]/total*100:.1f}%)")
print(f"Payroll:                             {query[1]:,} ({query[1]/total*100:.1f}%)")
print(f"Merchant:                            {query[2]:,} ({query[2]/total*100:.1f}%)")
print(f"BangorWealth:                        {query[3]:,} ({query[3]/total*100:.1f}%)")
print(f"PlingCustomer:                       {query[4]:,} ({query[4]/total*100:.1f}%)")
print(f"ABLECustomer:                        {query[5]:,} ({query[5]/total*100:.1f}%)")

TPS (Treasury and Payment Services): 2,872 (1.0%)
Payroll:                             5,066 (1.8%)
Merchant:                            1,257 (0.5%)
BangorWealth:                        2,239 (0.8%)
PlingCustomer:                       625 (0.2%)
ABLECustomer:                        1,930 (0.7%)

### Gender distribution

In [11]:
query = con.execute("""
    SELECT Gender, COUNT(*) as count
    FROM customers
    GROUP BY Gender
    ORDER BY count DESC
""").df()

print(query)

  Gender   count
0      M  104030
1      F  101410
2          70445
3      O     936
4      U      17

In [12]:
con.execute("""
    SELECT Individual, Gender, COUNT(*) as count
    FROM customers
    GROUP BY Individual, Gender
    ORDER BY Individual, count DESC
""").df()

  Individual Gender   count
0          N          39542
1          N      M     839
2          N      F      20
3          N      O       9
4          Y      M  103191
5          Y      F  101390
6          Y          30903
7          Y      O     927
8          Y      U      17

### Types of accounts and loans

In [13]:
query = con.execute("""
    SELECT 
        ROUND(AVG(NumberActiveDDAs), 2) AS avg_ddas,
        ROUND(AVG(NumberActiveTimeDeposits), 2) AS avg_time_deposits,
        ROUND(AVG(NumberActiveLoans), 2) AS avg_loans,
        ROUND(AVG(NumberCreditCardAccts), 2) AS avg_credit_cards,
        MAX(NumberActiveDDAs) AS max_ddas,
        MAX(NumberActiveTimeDeposits) AS max_time_deposits,
        MAX(NumberActiveLoans) AS max_loans,
        MAX(NumberCreditCardAccts) AS max_credit_cards
    FROM customers
""").fetchone()

print(f"{'Account Type':<25} {'Avg':<10} {'Max':<10}")
print(f"{'Active DDAs':<25} {query[0]:<10} {int(query[4]):<10}")
print(f"{'Active Time Deposits':<25} {query[1]:<10} {int(query[5]):<10}")
print(f"{'Active Loans':<25} {query[2]:<10} {int(query[6]):<10}")
print(f"{'Credit Card Accounts':<25} {query[3]:<10} {int(query[7]):<10}")

Account Type              Avg        Max
Active DDAs               1.87       227
Active Time Deposits      0.08       27
Active Loans              0.27       15
Credit Card Accounts      0.02       2

In [14]:
query = con.execute("""
                    SELECT CustomerID, NumberActiveDDAs
                    FROM customers
                    WHERE NumberActiveDDAs = 227
                    """).df()

print(query)

  CustomerID  NumberActiveDDAs
0  BSB343401             227.0

In [15]:
query = con.execute("""
                    SELECT *
                    FROM customers
                    WHERE CustomerID = 'BSB343401'            
                    """).df()

print(query.T)

                                              0
CustomerID                            BSB343401
Individual                                    N
Age                                         0.0
Gender
NAICSCode                              813410.0
OriginalCustomerDate        1982-01-20 00:00:00
RelationshipYears                          44.0
RelationshipMonths                        528.0
BangorWealth                              False
Payroll                                   False
Merchant                                  False
TPS                                       False
PlingCustomer                             False
ABLECustomer                              False
TimeDepositAccount                            N
DepositAccount                                Y
LoanAccount                                   N
CreditCardAccount                             N
ActiveATMCard                                 N
ActiveDebitCard                               Y
NumberActiveDDAs                          227.0
NumberActiveTimeDeposits                    0.0
NumberActiveLoans                           0.0
NumberCreditCardAccts                       0.0
PrimaryBankingCustomerFlag                    Y

### Primary Banking Customer Flag

In [16]:
query = con.execute("""
    SELECT PrimaryBankingCustomerFlag, COUNT(*) as count
    FROM customers
    GROUP BY PrimaryBankingCustomerFlag
    ORDER BY count DESC
""").df()

print(query)

  PrimaryBankingCustomerFlag   count
0                          Y  176425
1                          N  100413

### Oldest Customers

In [17]:
query = con.execute("""
    SELECT CustomerID, OriginalCustomerDate, RelationshipYears, Age, Individual
    FROM customers
    ORDER BY Age DESC
    LIMIT 25
""").df()

print(query)

   CustomerID OriginalCustomerDate  RelationshipYears    Age Individual
0   BSB505021           1982-01-21               44.0  126.0          Y
1   BSB104853           1970-06-29               56.0  126.0          Y
2   BSB197835           2019-04-10                7.0  126.0          N
3   BSB152620           2010-05-12               16.0  126.0          N
4   BSB179775           2004-01-22               22.0  125.0          N
5   BSB036562           1998-12-01               28.0  125.0          N
6   BSB455643           1992-08-21               34.0  120.0          Y
7   BSB170153           1996-10-03               30.0  118.0          Y
8   BSB169978           1989-11-08               37.0  118.0          Y
9   BSB368581           1977-03-21               49.0  115.0          Y
10  BSB160295           1986-05-21               40.0  114.0          Y
11  BSB323919           1985-06-17               41.0  114.0          Y
12  BSB383415           1969-01-01               57.0  114.0          Y
13  BSB193563           1982-06-01               44.0  113.0          Y
14  BSB257313           1986-11-18               40.0  113.0          Y
15  BSB475124           1985-08-23               41.0  111.0          Y
16  BSB020714           2011-04-26               15.0  111.0          Y
17  BSB131354           1994-02-28               32.0  110.0          Y
18  BSB229481           1982-05-01               44.0  110.0          Y
19  BSB384247           1990-09-21               36.0  109.0          Y
20  BSB305637           2016-12-23               10.0  109.0          Y
21  BSB105544           1989-06-30               37.0  109.0          Y
22  BSB455467           1984-12-04               42.0  108.0          Y
23  BSB274144           2001-05-25               25.0  108.0          Y
24  BSB504378           1995-02-17               31.0  108.0          Y

In [ ]:
query = con.execute("""
    SELECT *
    FROM customers
    WHERE Age > 100
    ORDER BY Age DESC
""").df()

print(query)

In [18]:
query = con.execute("""
    SELECT *
    FROM customers
    WHERE CustomerID = 'BSB505021'
""").df()

print(query.T)

                                              0
CustomerID                            BSB505021
Individual                                    Y
Age                                       126.0
Gender
NAICSCode                                   NaN
OriginalCustomerDate        1982-01-21 00:00:00
RelationshipYears                          44.0
RelationshipMonths                        528.0
BangorWealth                              False
Payroll                                   False
Merchant                                  False
TPS                                       False
PlingCustomer                             False
ABLECustomer                              False
TimeDepositAccount                            N
DepositAccount                                Y
LoanAccount                                   N
CreditCardAccount                             N
ActiveATMCard                                 N
ActiveDebitCard                               N
NumberActiveDDAs                            1.0
NumberActiveTimeDeposits                    0.0
NumberActiveLoans                           0.0
NumberCreditCardAccts                       0.0
PrimaryBankingCustomerFlag                    N